import Texture from '../prime/texture'
import Sound from '../prime/sound'

export default {
    game_title: new Texture('res/textures/game_title.png', 1, 1),
    menu_item_bg: new Texture('res/textures/menu_item_bg.png', 1, 1),
    menu_btn: new Texture('res/textures/menu_btn.png', 1, 1, 60, 60),
    star_full: new Texture('res/textures/star_full.png', 1, 1, 40, 40),
    star_empty: new Texture('res/textures/star_empty.png', 1, 1, 40, 40),
    stage_empty: new Texture('res/textures/stage_empty.png', 1, 1),
    paper_dog_thumb: new Texture('res/textures/paper_dog_thumb.png', 1, 1, 240, 240),
    paper_dog: new Texture('res/textures/paper_dog.png', 1, 1, 480, 480),
    paper_dog_piece: new Texture('res/textures/paper_dog.png', 3, 3, 120, 120),
    paper_happy_thumb: new Texture('res/textures/paper_happy_thumb.png', 1, 1, 240, 240),
    paper_happy: new Texture('res/textures/paper_happy.png', 1, 1, 480, 480),
    paper_happy_piece: new Texture('res/textures/paper_happy.png', 3, 3, 120, 120),
    paper_fish_thumb: new Texture('res/textures/paper_fish_thumb.png', 1, 1, 240, 240),
    paper_fish: new Texture('res/textures/paper_fish.png', 1, 1, 480, 480),
    paper_fish_piece: new Texture('res/textures/paper_fish.png', 3, 3, 120, 120),
    paper_shanxi_thumb: new Texture('res/textures/paper_shanxi_thumb.png', 1, 1, 240, 240),
    paper_shanxi: new Texture('res/textures/paper_shanxi.png', 1, 1, 480, 480),
    paper_shanxi_piece: new Texture('res/textures/paper_shanxi.png', 3, 3, 120, 120),
    paper_magpie_thumb: new Texture('res/textures/paper_magpie_thumb.png', 1, 1, 240, 240),
    paper_magpie: new Texture('res/textures/paper_magpie.png', 1, 1, 480, 480),
    paper_magpie_piece: new Texture('res/textures/paper_magpie.png', 3, 3, 120, 120),
    paper_horse_thumb: new Texture('res/textures/paper_horse_thumb.png', 1, 1, 240, 240),
    paper_horse: new Texture('res/textures/paper_horse.png', 1, 1, 480, 480),
    paper_horse_piece: new Texture('res/textures/paper_horse.png', 3, 3, 120, 120),
    ink: new Texture('res/textures/ink.png', 1, 1),
    painting_flower_thumb: new Texture('res/textures/painting_flower_thumb.png', 1, 1, 240, 240),
    painting_flower: new Texture('res/textures/painting_flower.png', 3, 3, 160, 160),
    painting_flower_piece: new Texture('res/textures/painting_flower.png', 3, 3, 120, 120),
    painting_bedroom_thumb: new Texture('res/textures/painting_bedroom_thumb.png', 1, 1, 240, 240),
    painting_bedroom: new Texture('res/textures/painting_bedroom.png', 3, 3, 160, 160),
    painting_bedroom_piece: new Texture('res/textures/painting_bedroom.png', 3, 3, 120, 120),
    painting_mother_thumb: new Texture('res/textures/painting_mother_thumb.png', 1, 1, 240, 240),
    painting_mother: new Texture('res/textures/painting_mother.png', 3, 3, 160, 160),
    painting_mother_piece: new Texture('res/textures/painting_mother.png', 3, 3, 120, 120),
    painting_kiss_thumb: new Texture('res/textures/painting_kiss_thumb.png', 1, 1, 240, 240),
    painting_kiss: new Texture('res/textures/painting_kiss.png', 3, 3, 160, 160),
    painting_kiss_piece: new Texture('res/textures/painting_kiss.png', 3, 3, 120, 120),
    painting_mona_lisa_thumb: new Texture('res/textures/painting_mona_lisa_thumb.png', 1, 1, 240, 240),
    painting_mona_lisa: new Texture('res/textures/painting_mona_lisa.png', 3, 3, 160, 160),
    painting_mona_lisa_piece: new Texture('res/textures/painting_mona_lisa.png', 3, 3, 120, 120),
    painting_cows_thumb: new Texture('res/textures/painting_cows_thumb.png', 1, 1, 240, 240),
    painting_cows: new Texture('res/textures/painting_cows.png', 3, 3, 160, 160),
    painting_cows_piece: new Texture('res/textures/painting_cows.png', 3, 3, 120, 120),
}