import Texture from '../prime/texture'
import Sound from '../prime/sound'

export default {
    menu_btn: new Texture('res/textures/menu_btn.png', 1, 1, 60, 60),
    star_full: new Texture('res/textures/star_full.png', 1, 1, 40, 40),
    star_empty: new Texture('res/textures/star_empty.png', 1, 1, 40, 40),
    stage_empty: new Texture('res/textures/stage_empty.png', 1, 1),
    chrysanthemum_thumb: new Texture('res/textures/chrysanthemum_thumb.png', 1, 1, 240, 240),
    chrysanthemum: new Texture('res/textures/chrysanthemum.png', 1, 1, 480, 480),
    chrysanthemum_piece: new Texture('res/textures/chrysanthemum.png', 3, 3, 120, 120),
    tree_thumb: new Texture('res/textures/tree_thumb.png', 1, 1, 240, 240),
    tree: new Texture('res/textures/tree.png', 1, 1, 480, 480),
    tree_piece: new Texture('res/textures/tree.png', 3, 3, 120, 120),
    lotus_thumb: new Texture('res/textures/lotus_thumb.png', 1, 1, 240, 240),
    lotus: new Texture('res/textures/lotus.png', 1, 1, 480, 480),
    lotus_piece: new Texture('res/textures/lotus.png', 3, 3, 120, 120),
    horse_thumb: new Texture('res/textures/horse_thumb.png', 1, 1, 240, 240),
    horse: new Texture('res/textures/horse.png', 1, 1, 480, 480),
    horse_piece: new Texture('res/textures/horse.png', 4, 4, 90, 90),
    bird_thumb: new Texture('res/textures/bird_thumb.png', 1, 1, 240, 240),
    bird: new Texture('res/textures/bird.png', 1, 1, 480, 480),
    bird_piece: new Texture('res/textures/bird.png', 4, 4, 90, 90),
    butterfly_thumb: new Texture('res/textures/butterfly_thumb.png', 1, 1, 240, 240),
    butterfly: new Texture('res/textures/butterfly.png', 1, 1, 480, 480),
    butterfly_piece: new Texture('res/textures/butterfly.png', 4, 4, 90, 90),
    ink: new Texture('res/textures/ink.png', 1, 1),
    flower_thumb: new Texture('res/textures/flower_thumb.png', 1, 1, 240, 240),
    flower: new Texture('res/textures/flower.png', 3, 3, 160, 160),
    flower_piece: new Texture('res/textures/flower.png', 3, 3, 120, 120),
    bedroom_thumb: new Texture('res/textures/bedroom_thumb.png', 1, 1, 240, 240),
    bedroom: new Texture('res/textures/bedroom.png', 3, 3, 160, 160),
    bedroom_piece: new Texture('res/textures/bedroom.png', 3, 3, 120, 120),
    mother_thumb: new Texture('res/textures/mother_thumb.png', 1, 1, 240, 240),
    mother: new Texture('res/textures/mother.png', 3, 3, 160, 160),
    mother_piece: new Texture('res/textures/mother.png', 3, 3, 120, 120),
    kiss_thumb: new Texture('res/textures/kiss_thumb.png', 1, 1, 240, 240),
    kiss: new Texture('res/textures/kiss.png', 3, 3, 160, 160),
    kiss_piece: new Texture('res/textures/kiss.png', 3, 3, 120, 120),
    mona_lisa_thumb: new Texture('res/textures/mona_lisa_thumb.png', 1, 1, 240, 240),
    mona_lisa: new Texture('res/textures/mona_lisa.png', 3, 3, 160, 160),
    mona_lisa_piece: new Texture('res/textures/mona_lisa.png', 3, 3, 120, 120),
    cows_thumb: new Texture('res/textures/cows_thumb.png', 1, 1, 240, 240),
    cows: new Texture('res/textures/cows.png', 3, 3, 160, 160),
    cows_piece: new Texture('res/textures/cows.png', 3, 3, 120, 120),
}